class Constants:
    def __init__(self):
        pass
    USER_TABLE = "user"
    SCHEDULE_TABLE = "schedule"



    ENVIRONMENT = "prod"

    PASSWORD_AND_NEW_PASSWORD_CANT_NOT_BE_SAME = "PASSWORD_AND_NEW_PASSWORD_CANT_NOT_BE_SAME"
    PASSWORD_AND_CONFIRM_PASSWORD_NOT_SAME = "PASSWORD_AND_CONFIRM_PASSWORD_NOT_SAME"
    DEVICE_NAME_ALREADY_EXISTS = "DEVICE_NAME_ALREADY_EXISTS"
    DEVICE_NAME_TOO_LONG = "DEVICE_NAME_TOO_LONG"
    USERNAME_PASSWORD_MISMATCH = "USERNAME_PASSWORD_MISMATCH"
    DEVICE_MAX_COUNT_REACHED = "DEVICE_MAX_COUNT_REACHED"
    INVALID_OR_EXPIRED_TOKEN = "INVALID_OR_EXPIRED_TOKEN"
    INVALID_CURRENT_PASSWORD = "INVALID_CURRENT_PASSWORD"
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
    DEVICE_ALREADY_EXISTS = "DEVICE_ALREADY_EXISTS"
    RULES_ALREADY_EXISTS = "RULES_ALREADY_EXISTS"
    NOT_AUTHENTIC_DEVICE = "NOT_AUTHENTIC_DEVICE"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    INVALID_JSON_FORMAT = "INVALID_JSON_FORMAT"
    PRECONDITION_FAILED = "PRECONDITION_FAILED"
    EXPECTATION_FAILED = "EXPECTATION_FAILED"
    UNAUTHORIZED = "UNAUTHORIZED"
    SERVER_ERROR = "SERVER_ERROR"
    BAD_REQUEST = "BAD_REQUEST"
    BAD_GATEWAY = 'BAD_GATEWAY'
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    SUCCESS = "SUCCESS"
    MULTI_STATUS = 'MULTI_STATUS'
    INSERT_QUERY_FAILED = "INSERT_QUERY_FAILED"
